#!/bin/bash

##############################################################################
#
# Fast way to boot the gdb
#
# @author Kirill Zhernov

##############################################################################

make clean

make

exetutable=$(find . -name "*.elf")

riscv64-unknown-elf-gdb -ex "target extended-remote localhost:3333" -ex "file $exetutable" -ex "load"
