#!/bin/bash

##############################################################################
#
# Sends string from specified file to specified tty and reports results to log
#
# @author Kirill Zhernov

##############################################################################

screen -L -Logfile test_results.log -d -m -S UART /dev/ttyUSB2 115200,cs8

screen -S UART -X readreg p $(pwd)/../uart_asm_rx/send_string

screen -S UART -X paste p

screen -S UART -X quit
